name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - run: go build -v ./...
      - run: go test -v ./...

      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kkweon-discord-ping-pong-bot"
          heroku_email: "kkweon@gmail.com"
